name: Deploy Backend to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Connected"

            cd ~/backend_portfolio

            echo "Fetching latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Restarting application..."
            pm2 restart portfolio-backend

            echo "Current commit:"
            git log --oneline -1

            echo "Deployment completed successfully."